export default {
    home: '/',
    signup: '/signup',
    signin: '/signin',
    signout: '/signout',
    users: '/users',
    browse: '/browse/:location',
    menu: '/menu/:id',
    checkout: '/summary',
    manageRestaurant: '/manage-restaurant',
    history: '/history',
    historyOrderDetails: '/history/:id',
    orders: '/orders',
    manageOrders: '/manage-orders/',
    orderDetailsRestaurant: '/manage-orders/:id',
    manageMenu: '/manage-menu/',
    manageMenuItem: '/manage-menu-item/:id',
    addMenuItem: '/add-menu-item/',
    manageRestaurantAdmin: '/manage-restaurants-admin',
    adminPanel: '/admin-panel',
}